bookmark/urls.py
from django.conf.urls import url
from .views import *

# url 파싱 및 라우팅을 담당하는 부분
urlpatterns = [
    url(r'^$', BookmarkListV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDetailV.as_view(), name='detail'),
    url(r'^create/$', BookmarkCreateV.as_view(), name="create"),
    url(r'^update/(?P<pk>\d+)/$', BookmarkUpdateV.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', BookmarkDeleteV.as_view(), name='delete'),
]

site_bookmark/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexPage

# 라우팅을 담당하는 부분
urlpatterns = [
    url(r'^$', IndexPage.as_view(), name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/', include("bookmark.urls", namespace="bookmark")), # namespace를 지정함으로써 식별할 수 있음
]

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Bookmark(models.Model):
    author = models.ForeignKey(User,null=True)
    title = models.CharField(max_length=100, blank=True, null=True) # Char 필드 생성
    url = models.URLField('url',unique=True)

    def __str__(self): # 어떤값을 보여줄지
        return self.title

bookmark/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import  ListView,DetailView,CreateView,DeleteView,UpdateView #리스트뷰와 디테일뷰를 불러옮
from .models import Bookmark
from django.contrib.auth.mixins import LoginRequiredMixin # 이걸 상속받으면, 어드민 권한만실행가능
# 컨트롤러의 역할을 함

class BookmarkListV(ListView): # 장고에서 미리 준비되어있는 리스트뷰를 사용함
    model = Bookmark

class BookmarkDetailV(DetailView): # 장고에서 미리 준비되어있는 디테일뷰를 사용함
    model = Bookmark

class BookmarkCreateV(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title','url']
    success_url = reverse_lazy('bookmark:index') # rediction

    def form_valid(self, form): # 장입
        form.instance.author_id = self.request.user.id # user 클래스의 id를 넣어줌

        if form.is_valid:
            form.instance.save()
            return redirect('/bookmark/')
        else :
            return self.render_to_response({'form':form})

class BookmarkDeleteV(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')  # rediction

class BookmarkUpdateV(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index') # rediction

site_bookmark/views.py
from django.views.generic.base import TemplateView

class IndexPage(TemplateView):
    template_name = "index.html"  # 템플릿지정

bookmark/templates/bookmark/bookmark_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
</head>
<body>
<h1>Bookmark Delete Confirmation</h1>
<form action="." method="post">
    {% csrf_token %}
    <p>
        Do you want to delte {{ object }}
        <input type="submit" value="Delete">
    </p>
</form>
</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark Detail</title>
</head>
<body>
    <h1>{{ object.url }}</h1>
    <h4>URL : <a href="n{{ object.url }} " target="_blank"></a></h4>
</body>
</html>

bookmark/templates/bookmark/bookmark_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark Create</title>
</head>
<body>
<h1>Bookmark Create Page</h1>
<form action="." method="post"> <!--action -> 어느페이지로 보낼지-->
    {% csrf_token %}        <!--현재 페이지가 변조가 되지 않았나 확인함(보안 사항)-->
    {{form.as_p}}           <!-- -->
    <input type="submit" value="OK">
</form>
</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark List</title>
</head>
<body>
    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
                <li>
                    <a href="{%  url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a>
                    <a href="{%  url 'bookmark:update' bookmark.id %}">[수정]</a>
                    <a href="{%  url 'bookmark:delete' bookmark.id %}">[삭제]</a>
                </li>
        {% endfor %}
    </ul>
    <a href="{%  url 'bookmark:create'  %}">[Bookmark 추가]</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Project</title>
</head>
<body>
    <a href="{% url 'bookmark:index' %}">Index</a>
</body>
</html>